### ISSUE TITLE
Create a new `CLA reviewer` sub-team

### ISSUE THREAD

**Issue by jezdez** [conda/governance#136]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

To facilitate the review of incoming Adobe Sign CLA signatures, we'll need to create a "CLA Reviewers" subteam per governance policy.

### Why is this needed?

@conda/steering-council Opinions on this proposal?

### Proposal

I'm proposing to form a new "CLA Reviewers" subteam to help with https://github.com/conda/infrastructure/issues/932

### Team Charter

Following the governance policy, this is a [static](https://github.com/conda-incubator/governance/tree/963a16ee02126229ec57614b000e3480d8cea26d#static-charter) charter with the condition that the new CLA Reviewers team only consists of steering council members for compliance reasons.

The "CLA Reviewers" subteam helps with reviewing, facilitating feedback and approving (or denying) incoming CLA documents, through a public pull request based process. 

The CLA documents will be accessible to the team via a NumFOCUS provided Google Drive or similar.

This new team will be responsible for taking on the work that the "Infrastructure" team has done while reviewing similar signed documents of the previous Anaconda Inc-specific CLA.

To reduce the risk of bottlenecks in processing new CLA documents, the team must have at least 3 active members, and automatically fall back to the whole conda steering council if that number falls below it.

#### Work areas

- review incoming signed CLA documents via Adobe sign
- approving PRs in the repository where new CLA requests arrive (e.g. `conda/infrastructure` or `conda/governance`) as PR based on the process described in https://github.com/conda/infrastructure/issues/932
- responding to requests by the rest of the conda steering council, NumFOCUS legal etc

#### Scope

The "CLA Reviewer" team works as delegates of the conda steering council and follows the Conda Code of Conduct.

Here are copies of the new NumFOCUS specific CLA (location not final):

- The updated CLA public documentation: https://acrobat.adobe.com/id/urn:aaid:sc:VA6C2:6d77823b-ba54-483f-aa7b-bec5a2f00ab6

- The actual CLA form to sign: https://acrobat.adobe.com/id/urn:aaid:sc:VA6C2:080a6efe-79c5-4934-b4f6-c018b04ea1e3

#### Proposed members:

- @jezdez
- @chenghlee
- @jaimergp
- @travishathaway
- ...

**Comment by jaimergp** [comment]
Add me please :)

**Comment by chenghlee** [comment]
I'm all for having this subteam, but I'm a little confused how this would work:

> any member of the new CLA Reviewers is _also_ a steering council member.

The way I'm reading it, this could dramatically increase the size of the steering council, which, e.g., could make getting quorum for CEP votes more complicated. Also, wouldn't the [shared funding rule](https://github.com/conda/governance?tab=readme-ov-file#shared-funding-membership-restrictions) imply that no more than two employees per company could be on this subteam?

I can see requiring a minimum number of steering council members to be present on this subteam, particularly to "[respond] to requests by the rest of the conda steering council or NumFOCUS legal".

(It's also quite possible that I'm mis-reading that clause.)

**Comment by jaimergp** [comment]
I think it's more about "only steering can be CLA reviewer", and not "a CLA reviewer will become steering".

**Comment by jezdez** [comment]
> I think it's more about "only steering can be CLA reviewer", and not "a CLA reviewer will become steering".

Yes, that’s what I meant, sorry for the confusion, I’ll update the proposal.

**Comment by jezdez** [comment]
I've added links to the two Adobe Acrobat hosted files (CLA documentation, that will be part of the regular conda docs) and the actual CLA form to sign in the future.

**Comment by jezdez** [comment]
@conda/steering-council 

### Vote

This proposal falls under the **["Sub-team Formation"](https://github.com/conda/governance/blob/3fe0950d7ee58637fb36b5c1249b83f0bc864a05/README.md#sub-team-formation)** policy of the [conda governance policy](https://github.com/conda-incubator/governance), please vote and/or comment on this proposal.

It needs **50 %** of the Steering Council to vote `yes` to pass.

To vote, please leave `yes`, `no` or `abstain` as comments below.

If you would like to propose changes to the current proposal or have questions, please leave a comment below as well.

**This vote will end on 2024-05-17, End of Day, [Anywhere on Earth](https://time.is/Anywhere_on_Earth) (AoE).**

**Comment by jezdez** [comment]
yes

**Comment by ocefpaf** [comment]
yes

**Comment by baszalmstra** [comment]
yes

**Comment by wolfv** [comment]
yes

**Comment by xhochy** [comment]
Yes

**Comment by jjhelmus** [comment]
yes

**Comment by chenghlee** [comment]
Yes

**Comment by kkraus14** [comment]
yes

**Comment by jaimergp** [comment]
yes

**Comment by mbargull** [comment]
Yes

**Comment by travishathaway** [comment]
Not a steering council member, but I would like to be added to this team to help with the CLA review process.

**Comment by jezdez** [comment]
## Voting Results

This was a standard, non-timed-out vote.

Among [Steering Council members](https://github.com/conda/governance/blob/e30676d2cc16545a495b4b09ab4ada0a63f5836c/steering.csv) there are 7 "yes", 0 "no", and no abstentions.

Amone [Emeritus Steering Council members](https://github.com/conda/governance/blob/3fe0950d7ee58637fb36b5c1249b83f0bc864a05/emeritus.csv) there are 1 "yes", 0 "no", and no abstentions.

This vote **has NOT reached quorum** (7 is not at least 50% of 15).

This proposal has not passed.

**Comment by jezdez** [comment]
(note: this vote was at first erroneously called not having reached quorum and passing due GitHub hiding some of the votes as spam 🤦🏻)

## Voting Results

This was a standard, non-timed-out vote.

Among [Steering Council members](https://github.com/conda/governance/blob/e30676d2cc16545a495b4b09ab4ada0a63f5836c/steering.csv) there are 10 "yes", 0 "no", and no abstentions.

Among [Emeritus Steering Council members](https://github.com/conda/governance/blob/3fe0950d7ee58637fb36b5c1249b83f0bc864a05/emeritus.csv) there are 1 "yes", 0 "no", and no abstentions.

This vote **has reached quorum** (10 is at least 50% of 15 active steering council members).

It **has also passed** since it recorded 11 "yes" votes and 0 "no" votes giving 11/11 which is greater than 50% of 11.

**Comment by jezdez** [comment]
I've created the @conda/cla-reviewers team and populated it with the members listed in the issue description. Please let me know if anyone in the @conda/steering-council has feedback or wants to participate in the upcomgin process.

To facilitate the review and storage of CLA applications and signees, I've also created a new https://github.com/conda/cla repo, to have a single source of truth who has signed the new CLA (but not store the actual PDFs of course). I've assigned that repo _also_ to the steering council.
