### ISSUE TITLE
Request for incubation: `conda-protect`

### ISSUE THREAD

**Issue by jaimergp** [conda/governance#138]
* Project URL: https://github.com/travishathaway/conda-protect
* Comes from https://github.com/travishathaway/conda-protect/issues/5
* Members of the `conda-protect` team: @travishathaway

Adding this for historical record. If I don't hear from any objections, I'll proceed with the transfer in a few days.

**Comment by travishathaway** [comment]
Just commenting to confirm my willing participation 😀

**Comment by jaimergp** [comment]
Done :)
