### ISSUE TITLE
Request for incubation: `conda-pypi`

### ISSUE THREAD

**Issue by jaimergp** [conda/governance#142]
* Project URL: https://github.com/jaimergp/conda-pypi
* Comes from https://github.com/jaimergp/conda-pypi/issues/25
* Members of the `conda-pypi` team: @jaimergp, @jezdez 

Adding this for historical record. If I don't hear from any objections, I'll proceed with the transfer.

**Comment by jezdez** [comment]
I'd like to participate in the team if you have me

**Comment by jaimergp** [comment]
Done!
