### ISSUE TITLE
Request for incubation: `conda-checkpoints`

### ISSUE THREAD

**Issue by jaimergp** [conda/governance#144]
* Project URL: https://github.com/jaimergp/conda-checkpoints
* Members of the `conda-checkpoints` team: @jaimergp

Adding this for historical record. If I don't hear from any objections, I'll proceed with the transfer.

**Comment by jakirkham** [comment]
No objection. Though am curious how this compares to Conda revisions

* https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#restoring-an-environment
* https://blog.rtwilson.com/conda-revisions-letting-you-rollback-to-a-previous-version-of-your-environment/
* https://stackoverflow.com/a/56069934

**Comment by jaimergp** [comment]
I'd say conda revisions are conceptually broken. They don't guarantee a rollback; instead they will attempt to revert the action by solving the opposite operation against the current repodata. This means that (1) the solver runs for no reason, (2) there's an opportunity for errors.

With checkpoints I'm instead writing down the state of the environment as it was (at least the package records are there). If you wish to restore, you only need to take that lockfile and `conda create -n env-copy --file ...` it.

This is a good question to answer in the (eventual) documentation, so thanks for bringing it up!

**Comment by jaimergp** [comment]
Done!

- [Repo](https://github.com/conda-incubator/conda-checkpoints)
- [Team](https://github.com/orgs/conda-incubator/teams/conda-checkpoints)
