### ISSUE TITLE
Request for incubation: conda-rich

### ISSUE THREAD

**Issue by travishathaway** [conda/governance#191]
I would like to have this project added to conda-incubator:

- https://github.com/travishathaway/conda-rich

This is a new plugin that will add improved progress bars to conda via the [reporter-backends plugin hook](https://docs.conda.io/projects/conda/en/stable/dev-guide/plugins/reporter_backends.html).

cc: @jaimergp or @jezdez

**Comment by beckermr** [comment]
I think you need to initiate the transfer on your end and we can accept?

**Comment by jezdez** [comment]
@travishathaway I've created the @conda-incubator/conda-rich GitHub team and made you a maintainer in it, when you initiate the transfer, please select the team

**Comment by travishathaway** [comment]
@jezdez,

I'm not sure I added the team to the repository. Could you double check? I not longer have the ability to adjust the repositories settings.

**Comment by jaimergp** [comment]
Check now.

**Comment by jezdez** [comment]
I've also added @ForgottenProgramme to the team FWIW

**Comment by jezdez** [comment]
Closing as fixed.
