### ISSUE TITLE
Move conda governance related repos to the main conda organization

### ISSUE THREAD

**Issue by jezdez** [conda/governance#80]
Related to the currently running application to the NumFOCUS fiscal sponsorship, I'd like to formerly propose a few steps to clear up some organizational debt we've accrued over the years:

- [x] #135
- [x] Move the following repos from the conda-incubator to the conda GitHub organization:
  - [x] [governance](https://github.com/conda-incubator/governance)
  - [x] [ceps](https://github.com/conda-incubator/ceps)
  - ~[conda-dot-org](https://github.com/conda-incubator/conda-dot-org)~
  - [x] [assets](https://github.com/conda-incubator/assets)

Any other things we should fix at the same time?

**Comment by beckermr** [comment]
the website and assets repos should move over too

**Comment by jezdez** [comment]
I've moved all but conda-dot-org to the conda organization, simply because https://github.com/conda-incubator/conda-dot-org/issues/110 is unresolved.

Closing as fixed!
